### PR TITLE
Fix two maintenance issues

### PR DESCRIPTION
**Pull request by tarsius**
Please see the commit messages.

### CODE REVIEW

**Comment by tarsius** [comment]
Okay so the test fail...

Probably my second change is not correct. But I don't know what would be correct, just that what you are currently doing is not correct either. I shouldn't be asked about `elisp-lint-indent-specs` when opening e.g. a Dired buffer.

Please also fix the instructions in `elisp-lint`'s README as soon as possible. Also, if that variable is safe to be set as a file-local variable, then you should declare it as such.

**Comment by gonewest818** [comment]
Thanks for taking a look at this. I'm curious how you came across it, though. Were you just driving around the neighborhood and fixing up "broken windows"? Or did you follow the trail of the recent `elisp-lint` publish to the author, and then to my other projects?  Because AFAIK none of this should have affected the MELPA packaging or use of `adafruit-wisdom.el`.

Anyway:
* In your pull request, whatever you did caused the tests to run without `((indent-tab-mode . nil) (fill-column . 80))` which would lead to the [elisp-lint errors in Travis CI](https://travis-ci.org/gonewest818/adafruit-wisdom.el/jobs/342996361#L1093). I'll concentrate on marking the variable safe.
* I'm putting `test/` on the `load-path` in `.emacs/init.el`, to allow the test cases to `(require 'undercover-init)`.
* I'm experimenting with this mini `.emacs` init for CI rather than use Cask because of the maintainer situation. Also because installing Cask in Travis CI on recent Emacs versions has been a problem lately... which itself is a long story that unwinds back to gnutls-cli and the TLS cert on elpa.gnu.org:443. Long story short, I'm having to use all that machinery in `travis-ci/*.sh`, and in fact so is CIDER and I don't like it at all.
* I'm not sure about the [coverage warning](https://travis-ci.org/gonewest818/adafruit-wisdom.el/jobs/342996361#L1120), but if undercover isn't on the load path then that would do it.

**Comment by tarsius** [comment]
Sorry for this sloppy pull-request - I should have put more information into it up front.

> I'm curious how you came across it, though. Were you just driving around the neighborhood and fixing up "broken windows"?

I maintain the [Emacsmirror](https://emacsmirror.net) and as part of that I check for feature conflicts between all mirrored packages (and also for some other issues). As a result [hardly any remain](https://emacsmirror.net/stats/issues.html).

> Or did you follow the trail of the recent elisp-lint [Melpa pull-request]

That's how I learned that you are the maintainer now. If I had realized earlier, then I probably would have put in more effort right away.

----

Let us concentrate on the issue with the file-local variables first, because that could turn into a huge amount of work for me if we don't quickly nip it in the bud. For what it can mean for me if a package whose purpose has something to do with promoting best practices but ends up promoting or unintentionally encouraging a bad practice instead see https://github.com/rejeep/ert-runner.el/issues/38.

**The issue is that the scope of settings defined in `.dir-locals.el` has to be limited to the appropriate files/buffers.**

Yesterday I updated all mirrored packages a process that was interrupted by Emacs asking me to verify that I wanted to put some local variables into affect. I refused to do that and took a note to look into that at a later time because that should not happen - as part of the update process my tools look at the elisp files, but when doing that they explicitly suppress setting local variables and questions about doing that.

The reason this happens anyway for your package is that it also tries to set local variables in other buffers. It does so in every buffer whose `default-directory` is within the scope of `.dir-locals.el`.

I could suppress that too, but since yours is the only package that has this issue I would rather not, making it possible to detect similar issues in other packages in the future.

*So let's look at how you could fix the issue.*

This is what you have now:

```
((nil . ((indent-tabs-mode . nil)
         (fill-column . 80)
         (elisp-lint-indent-specs . ((describe . 1)
                                 (xdescribe . 1)
                                 (it . 1)
                                 (xit . 1)
                                 (before-each . 0)
                                 (before-all . 0)
                                 (after-each . 0)
                                 (after-all . 0))))))
```

I assumed - and still assume - that does settings are only intended to apply to `emacs-lisp-mode` buffers. So I replaced `nil` with `emacs-lisp`... which is wrong it should be `emacs-lisp-mode`. I have just pushed a fixed commit.

*Please* update the `elisp-lint` README, replacing that `nil` with `emacs-lisp-mode` there too.

**Comment by gonewest818** [comment]
Ok, gotcha. I understand the urgency.

**Comment by gonewest818** [comment]
By the way you're looking at an old commit or the wrong branch -- `lintel` was the name of my fork of `elisp-lint`, the fork existed for a narrow window and used (probably) only by me.

**Comment by tarsius** [comment]
And now for the other issue:

Bundling third-party libraries is bad practice. They tend to not get updated. This isn't much of an issue for users who install packages using `package.el` because those packages typically strip the bundled libraries again. However is a problem for the most useful users, those who run your package from the repository because they want to contribute to it.

Likewise it is an issue for users of alternative package managers, which may not be able to remove those files. My [Borg](https://emacsmirror.net/manual/borg/) package manager for example installs packages by cloning the upstream Git repository.

*Okay so how do we fix this?*

Well typically you should just remove the bundled library and instead add the respective package as a dependency. You cannot do that here because `undercover` isn't available from Melpa (or the Emacsmirror). I'll look into why that is so.

The short-time fix is to prevent `test/` from being added to the `load-path` and then explicitly (i.e. using the appropriate path) loading it in your build and/or test utilities. If I understood correctly that's what you plan to do.

**Comment by tarsius** [comment]
> By the way you're looking at an old commit or the wrong branch -- lintel was the name of my fork of elisp-lint, the fork existed for a narrow window and used (probably) only by me.

I've adjusted the above code block accordingly. 😉

**Comment by tarsius** [comment]
Ah wait `undercover` *is* available from Melpa and the Emacsmirror.

**Comment by gonewest818** [comment]
I'm distracted slightly because I have family commitments that I'm interleaving with keyboard. I did just push the documentation fix to `elisp-lint`.  I'm testing the implementation of that here but still broken.

**Comment by tarsius** [comment]
No problem -- I need to *eat*. See you later 🍰

**Comment by gonewest818** [comment]
Well, except I'm not bundling undercover. I'm just (perhaps ill-advisedly) following what the undercover package maintainer [does in his integration example](https://github.com/sviridov/undercover.el-buttercup-integration-example/blob/master/tests/undercover-init.el). 

In other words, I get what you're objecting to, but that's not what's happening. I double checked the result of `make recipes/adafruit-wisdom` to be certain.

I'll take another look at this when I have a chance.

**Comment by tarsius** [comment]
> Well, except I'm not bundling undercover.

I've realized that by now... with a full stomach and all.

> I'm just (perhaps ill-advisedly) following what the undercover package maintainer does in his integration example.

I'll have to talk to them. Provided that `undercover` loads `undercover-init.el` from some predetermined location (which it should) the `provide` form is not actually required.

**Comment by gonewest818** [comment]
Take a look at these changes.

 https://github.com/gonewest818/adafruit-wisdom.el/tree/emacsmirror-fixes/test 

`undercover-init.el` is not a part of undercover… it’s just a convention the author suggests for bootstrapping the coverage instrumentation prior to running your tests.  So the naming conflict is just people following the same convention. Since `undercover-init` is not really a “package” either, I removed the `provide`and also changed `test-adafruit-wisdom.el` to `load-file` the file directly rather than `require` like a package. I don’t know the guts of emacsmirror but my hope is this will make `undercover-init.el` look like an ordinary implementation file and not trigger your warning flags.

**Comment by tarsius** [comment]
> `undercover-init.el` is not a part of undercover… it’s just a convention the author suggests for bootstrapping the coverage instrumentation prior to running your tests.

Ah. In the case of `ert-runner` the respective file (`test-helper.el`) is actually loaded by the testing framework. But looking at your `undercover-init.el` things seem to work the other way around here - `undercover-init.el` (or whatever) is responsible for loading `undercover`.

**Comment by tarsius** [comment]
Opened an issue at https://github.com/sviridov/undercover.el-buttercup-integration-example/issues/1.

**Comment by gonewest818** [comment]
I think I'm pretty close on my branch, do you agree?  Although I'm getting really tired of Travis CI builds hanging for > 10 minutes (seriously? this is such a trivial project and make test takes seconds to run locally).

**Comment by gonewest818** [comment]
Thanks @tarsius, pls let me know if you see anything else.

**Comment by tarsius** [comment]
Thanks! (So far I haven't seen anything else and the fix seems to work.)

**Pull request closed without merging**
